name: Git is clean
on: [push]

jobs:
  git-clean:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - run: exit 1

      # - name: Install Nix 1/2
      #   uses: DeterminateSystems/nix-installer-action@main
      #   with:
      #     determinate: true
      # - name: Install Nix 2/2
      #   uses: DeterminateSystems/flakehub-cache-action@main

      # - name: Prepare Sushi Lib
      #   run: ./prep-sushi.sh

      # - name: Install Dependencies
      #   run:  nix develop -c npm install

      # - name: Lint
      #   run:  nix develop -c npm run lint

      # - run: git diff --exit-code

      # - uses: rainlanguage/github-chore/.github/actions/npm-blacklist@main

      - name: Send Telegram notification
        if: always()  # This ensures it runs regardless of previous step outcomes
        uses: rainlanguage/github-chore/.github/actions/telegram-status-report@2025-12-15-tg-ci-status-reporter
        with:
          status: ${{ job.status }}
          message: "some extra msgggggg"
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
